services:
  bayrobweb:
    build:
      context: .
      dockerfile: Dockerfile
#    image: "bayrob-web-img"
    container_name: bayrob-web-container
    working_dir: /bayrob-dev/src/bayrob/web
    command: 'python3 server.py -p 5005 -i "0.0.0.0"'
    environment:
      - "PYTHONUNBUFFERED:1"
    ports:
      - "5005:5005"