/* _src/pages/index.typ */
#let this = "_src/pages/index.typ"
#let highlight = "_src/common/highlight.typ"
#set heading(numbering: "1.")

// #set document(title: "BayRoB Docs")

#import "/_src/mod.typ": css, struct, excerpt, js, bayrob
#import struct: text, box, table, align

#include "/_src/common/common.typ"

= BayRoB

== About

#bayrob is a fully operational system combining joint probability distributions to generate action models from a
robot's experience data. Probabilistic action models can be queried using the provided web application and action
sequences can be refined/generated by performing an A\*-like backward or forward search and updating the robot's
probabilistic belief state according to the prospected results (or preconditions) of the respective steps.

If you are a developer, see #link("devs.html")[For Developers] for
examples how to execute learning and reasoning and the API for further documentation.

If you are a user, go to #link("users.html")[For Users] to find out how to use the tools in the project's web interface.

== Release notes

  - Release 1.0.0 (May 2024)

    - *Initial Release*

== Citing

When you publish research work that makes use of this software, we gratefully appreciate if a reference to #bayrob
can be found in your work in the following way:

#excerpt.code("@software{picklumbayrob,
    author  = {Picklum, Mareike},
    title   = {BayRoB},
    url     = {https://github.com/mareikep/bayrob},
    version = {1.0.0},
}", lang: "bibtex")

```ini
@software{picklumbayrob,
    author  = {Picklum, Mareike},
    title   = {BayRoB},
    url     = {https://github.com/mareikep/bayrob},
    version = {1.0.0},
}
```

The PhD thesis @picklum2024phd gives further insight about the capabilities of this software. For citations, the following Bibtex entry can be used for documents based on LaTeX:

```yaml
@phdthesis{picklum2024phd,
    author           = {Mareike Picklum},
    title            = {Probabilistic Action Prospection based on Experiences - 
    Representation, Learning and Reasoning in Autonomous Robotic Agents},
    year             = {2024},
    school           = {Universität Bremen},
    keywords         = {Probabilistic Inference; Robotics; action model; },
    doi              = {10.26092/elib/2990},
    bib2html_pubtype = {PhD Thesis},
    bib2html_rescat  = {Representation, Learning, Reasoning, Models, Actions}
}
```

//=============================================================================

== Contents
 
- #link("users.html")[For Users]
- #link("devs.html")[For Developers]
- #link("index.html")[BayRoB]
- #link("setup.html")[Setup]

//=============================================================================

== Credits

=== Lead Developer

Mareike Picklum (#link("mailto:mareikep@cs.uni-bremen.de")[mareikep\@cs.uni-bremen.de])

//=============================================================================

=== Contributors (JPT)

- Daniel Nyga
- Tom Schierenbeck

//=============================================================================

=== Acknowledgments

This work has received funding from the Collaborative Research Center (CRC)
SFB1232 #link("http://www.uni-bremen.de/farbige-zustaende.html")[Farbige Zustaende]
by the German Research Foundation (Deutsche Forschungsgemeinschaft
(DFG)) (project number 276397488), from the European Union Seventh Framework
Programme (FP7) projects RoboHow (grant number 288533) and SHERPA (grant
number 600958) and from Research Grants DFG Programme PIPE (project number
322037152).

#let gray-box = box(
  inline: false, class: "cell",
  fill: "var(--dk-gray1)", height: 3cm, outset: 3pt, inset: 5pt,
)
#let my-aligned-box(alignment, inner) = {
  gray-box({
    align(alignment)[#inner]
  })
}
#table(columns: 4, gutter: 3mm, {
  my-aligned-box(center)[
    #html.a(href: "http://dfg.de", {
      html.img(src: "_assets/img/dfg.jpg", height: 100, alt: "DFG")
    })
  ]
  my-aligned-box(center)[
        #html.a(href: "http://www.uni-bremen.de/farbige-zustaende.html", {
      html.img(src: "_assets/img/logo_sfb_orig.png", height: 100, alt: "SFB Farbige Zustaende")
    })
  ]
  my-aligned-box(center)[
    #html.a(href: "https://robohow.org/index.html", {
      html.img(src: "_assets/img/robohowcog-logo.jpg", height: 100, alt: "RoboHow")
    })
  ]
  my-aligned-box(center)[    
    #html.a(href: "https://sherpa-project.eu/", {
      html.img(src: "_assets/img/sherpa.png", height: 100, alt: "Sherpa")
    })
  ]
})

//=============================================================================

== Publications

#bibliography("/_assets/refs.bib", title: none, style: "apa")

//=============================================================================
