# Book settings

title: BayRoB
author: Mareike Picklum
logo: _static/images/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  extra_extensions:
    - myst_nb
    - sphinxcontrib.bibtex
    - autoapi.extension
    - 'sphinx.ext.autodoc'
    - sphinxcontrib.plantuml
  config:
    bibtex_bibfiles:
      - references.bib
    # AutoAPI configuration - only generate docs for core and models
    autoapi_dirs:
      - ../src/bayrob
    autoapi_type: python
    autoapi_root: autoapi
    autoapi_options:
      - members
      - undoc-members
      - show-inheritance
      - show-module-summary
      - imported-members
    autoapi_ignore:
      - '*/tests/*'
      - '*/test_*.py'
      - '*_ext.pyx'
      - '*_ext.c'
      - '*/application/*'
      - '*/config.py'
      - '*/logs/*'
      - '*/utils/*'
      - '*/web/*'
    autoapi_add_toctree_entry: false
    autoapi_keep_files: true
    autoapi_python_class_content: both
    autoapi_member_order: groupwise
    suppress_warnings:
      - "etoc.toctree"
      - "etoc.ref"
      - "autoapi"

# Information about where the book exists on the web
repository:
  url: https://github.com/mareikep/bayrob
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
